### ISSUE TITLE
Crash when using Cloud Storage StorageImage

### ISSUE THREAD

**Issue by tarscher** [FirebaseExtended/reactfire#395]
### Version info

**React:**
17.0.2
**Firebase:**
^8.6.8
**ReactFire:**
3.0.0-rc.0
**Other (e.g. Node, browser, operating system) (if applicable):**
"nextjs": "^11.0.1",
Node: 14
### Test case

```
import { StorageImage } from "reactfire";

export default function Survey() {
  return (
    <div>
      <StorageImage storagePath={"userPhotos/default.jpg"} />
    </div>
  );
}
```

### Actual behavior
C:\box2\app\node_modules\@firebase\storage\dist\index.cjs.js:510
        this.xhr_ = new XMLHttpRequest();
                        ^

ReferenceError: XMLHttpRequest is not defined
    at new NetworkXhrIo (C:\box2\app\node_modules\@firebase\storage\dist\index.cjs.js:510:25)
    at XhrIoPool.createXhrIo (C:\box2\app\node_modules\@firebase\storage\dist\index.cjs.js:637:16)
    at doTheRequest (C:\box2\app\node_modules\@firebase\storage\dist\index.cjs.js:1042:34)
    at Timeout._onTimeout (C:\box2\app\node_modules\@firebase\storage\dist\index.cjs.js:835:13)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
error Command failed with exit code 1.

**Comment by jhuleatt** [comment]
Hi @tarscher, The Firebase Storage SDK (which StorageImage is using under the hood) is meant to be run in the browser, where `XMLHttpRequest` is built-in. You'll have to either [polyfill](https://github.com/vercel/next.js/discussions/17404#discussioncomment-86126) or make sure that this component only renders client-side
